import asyncio
import datetime
from typing import Optional
from zoneinfo import ZoneInfo

# Google ADK Imports
from google.adk.runners import Runner
from google.adk.agents import Agent
from google.adk.models.lite_llm import LiteLlm
from google.adk.sessions.in_memory_session_service import InMemorySessionService
from google.genai import types

# 1. Define the Shared Model (Ollama via LiteLlm)
OLLAMA_MODEL = LiteLlm(model="ollama_chat/mistral-small3.2")

# --- STEP 1: Define Tools ---
def get_weather(city: str) -> dict:
    """Retrieves the current weather report for a specified city."""
    if city.lower() == "new york":
        return {"status": "success", "report": "The weather in New York is sunny and 25°C."}
    return {"status": "error", "error_message": f"Weather for '{city}' not available."}

def get_current_time(city: str) -> dict:
    """Returns the current time in a specified city."""
    if city.lower() == "new york":
        tz = ZoneInfo("America/New_York")
        now = datetime.datetime.now(tz)
        return {"status": "success", "report": f"Current time: {now.strftime('%H:%M:%S')}"}
    return {"status": "error", "error_message": "Timezone not found."}

def say_hello(name: Optional[str] = None) -> str:
    """Provides a simple greeting."""
    return f"Hello, {name}!" if name else "Hello there!"

def say_goodbye() -> str:
    """Provides a simple farewell message."""
    return "Goodbye! Have a great day."

# --- STEP 2: Define Sub-Agents ---
greeting_agent = Agent(
    model=OLLAMA_MODEL,
    name="greeting_agent",
    instruction="Your ONLY task is to greet the user using the 'say_hello' tool.",
    tools=[say_hello],
)

farewell_agent = Agent(
    model=OLLAMA_MODEL,
    name="farewell_agent",
    instruction="Your ONLY task is to say goodbye using the 'say_goodbye' tool.",
    tools=[say_goodbye],
)

# --- STEP 3: Define Root Agent (The Coordinator) ---
weather_agent_team = Agent(
    name="weather_coordinator",
    model=OLLAMA_MODEL,
    instruction=(
        "You are the lead coordinator. "
        "1. If it's a greeting, delegate to 'greeting_agent'. "
        "2. If it's a farewell, delegate to 'farewell_agent'. "
        "3. If it's weather or time, handle it yourself using your tools."
    ),
    tools=[get_weather, get_current_time],
    sub_agents=[greeting_agent, farewell_agent]
)

# --- STEP 4: Execution Logic ---
async def run_team_conversation():
    print("--- Starting Agent Team Conversation (Ollama) ---\n")
    
    # 1. Create a persistent Session Service instance
    session_service = InMemorySessionService()
    
    # 2. Initialize Runner with both Agent AND app_name
    # Note: app_name is mandatory to define the namespace for sessions.
    runner = Runner(
        agent=weather_agent_team,
        session_service=session_service,
        app_name="weather_app"
    )

    user_id = "user_123"
    session_id = "session_abc"

    # 3. Create the session explicitly in the service
    # The app_name MUST match the Runner's app_name
    await runner.session_service.create_session(
        user_id=user_id,
        session_id=session_id,
        app_name="weather_app"
    )

    queries = [
        "Hello! My name is Alex.",
        "What is the weather in New York?",
        "What time is it in New York?",
        "Thanks for the help, goodbye!"
    ]

    for query in queries:
        print(f"\nUSER: {query}")
        
        # 4. Wrap query in Content/Part object to avoid 'str' attribute errors
        user_message = types.Content(
            role="user",
            parts=[types.Part.from_text(text=query)]
        )
        
        try:
            # 5. Run the conversation turn
            async for event in runner.run_async(
                new_message=user_message,
                user_id=user_id,
                session_id=session_id
            ):
                # Print only the text content generated by the agents
                if hasattr(event, 'content') and event.content:
                    for part in event.content.parts:
                        if part.text:
                            print(f"AGENT: {part.text}")
        except Exception as e:
            print(f"Error during runner execution: {e}")

if __name__ == "__main__":
    try:
        asyncio.run(run_team_conversation())
    except Exception as e:
        print(f"An error occurred: {e}")
